# Generated by Django 4.2.1 on 2023-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('occupation', models.CharField(choices=[('nursing', 'Nursing'), ('software_engineer', 'Software Engineer'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('lawyer', 'Lawyer'), ('accountant', 'Accountant'), ('designer', 'Designer'), ('mechanic', 'Mechanic'), ('chef', 'Chef'), ('salesperson', 'Salesperson'), ('pilot', 'Pilot'), ('architect', 'Architect'), ('police_officer', 'Police Officer'), ('journalist', 'Journalist'), ('artist', 'Artist'), ('engineer', 'Engineer')], max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('application_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
