# Generated by Django 4.2.1 on 2023-08-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
